### ISSUE TITLE
사용자가 많아지니 죽네.

### ISSUE THREAD

**Issue by mins01** [mins01/nodejs_chat#1]
Chat.error() [User#a1gxntn71xp3g] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
internal/tty.js:128
    if (/^xterm-256/.test(env.TERM))
                     ^

RangeError: Maximum call stack size exceeded
    at RegExp.test (<anonymous>)
    at WriteStream.getColorDepth (internal/tty.js:128:22)
    at Console.(anonymous function) (console.js:183:16)
    at Console.(anonymous function) (console.js:190:40)
    at Console.log (console.js:202:31)
    at Chat.onerror (/home/new10/www/ex/nodejs_chat/server/Chat.js:73:11)
    at Connection.<anonymous> (/home/new10/www/ex/nodejs_chat/server/Chat.js:45:9)
    at Connection.emit (events.js:189:13)
    at Socket.<anonymous> (/home/new10/www/ex/nodejs_chat/node_modules/nodejs-websocket/Connection.js:70:8)
    at Socket.emit (events.js:189:13)

**Comment by mins01** [comment]
브라우저에서 F5 계속 누르면 접속이 끊어져서 메세지 처리에 문제가 생김
try catch 로 해당 부분 무시하도록 함
conn.sendText() 부분
